# Generated by makegen....

TARGET = test-umor
OBJECTS = test-umor.o

CC = gcc
CFLAGS =   $(INCDIR)

LIBS = -lncurses
LIBDIR = -L/usr/lib
INCDIR = -I/usr/include

INSTALLDIR = 

all: $(TARGET)

$(TARGET): $(OBJECTS)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJECTS) $(LIBDIR) $(LIBS)

clean:
	rm -f a.out core *~ \#* *.bak $(TARGET) $(OBJECTS)

